test: disable internal metrics endpoint for internal OTel Collector (#471)
The OpenTelemetry Collector spawned via the OpenTelemetry Lambda extension binds its internal telemetry listener to `127.0.0.1:8888` which is in conflict with the default metrics listener in OpenTelemetry Collector, so that it won't be able to start.

Log message from the OpenTelemetry Lambda extension:
```
{
    "level": "Basic",
    "ts": 1756966825.8117547,
    "caller": "service@v0.98.0/telemetry.go:97",
    "msg": "Serving metrics",
    "address": "localhost:8888"
}
```

Log message from the OpenTelemetry Collector under test:
```
Error: failed to create SDK: binding address localhost:8888 for Prometheus exporter: listen tcp 127.0.0.1:8888: bind: address already in use
```